In [1]:
import pandas as pd
import math

In [2]:
test_f = pd.read_csv('fifa.csv')
test_p = pd.read_json('pl.json').transpose()
cleanP = test_p.reset_index()
cleanP = cleanP.rename(columns = {'index':'Name'}, inplace = True)

In [17]:
test_l = pd.read_csv('ll.csv')

In [28]:
list(cleanP.columns)

['Name',
 'Club',
 'Position',
 'Appearances',
 'Goals',
 'Wins',
 'Losses',
 'Attack',
 'Goals Per Match',
 'Goals With Header',
 'Goals With Right Foot',
 'Goals With Left Foot',
 'Penalties Scored',
 'Goals From Freekick',
 'Shots',
 'Shots On Target',
 'Shooting Accuracy %',
 'Hit Woodwork',
 'Big Chances Missed',
 'Team Play',
 'Assists',
 'Passes',
 'Passes Per Match',
 'Big Chances Created',
 'Crosses',
 'Cross Accuracy %',
 'Through Balls',
 'Accurate Long Balls',
 'Discipline',
 'Yellow Cards',
 'Red Cards',
 'Fouls',
 'Offsides',
 'Defence',
 'Tackles',
 'Tackle Success %',
 'Blocked Shots',
 'Interceptions',
 'Clearances',
 'Headed Clearance',
 'Recoveries',
 'Duels Won',
 'Duels Lost',
 'Successful 50/50s',
 'Aerial Battles Won',
 'Aerial Battles Lost',
 'Errors Leading To Goal',
 'Goals per match',
 'Headed goals',
 'Goals with right foot',
 'Goals with left foot',
 'Penalties scored',
 'Freekicks scored',
 'Shots on target',
 'Shooting accuracy %',
 'Hit woodwork',
 'Big chances missed',
 'Passes per match',
 'Big chances created',
 'Yellow cards',
 'Red cards',
 'Blocked shots',
 'Clean sheets',
 'Goals conceded',
 'Tackle success %',
 'Last man tackles',
 'Clearances off line',
 'Duels won',
 'Duels lost',
 'Aerial battles won',
 'Aerial battles lost',
 'Own goals',
 'Errors leading to goal',
 'Cross accuracy %',
 'Through balls',
 'Accurate long balls',
 'Goalkeeping',
 'Saves',
 'Penalties saved',
 'Punches',
 'High Claims',
 'Catches',
 'Sweeper clearances',
 'Throw outs',
 'Goal Kicks',
 'Successful 5/5s',
 'Successful 0/0s',
 'Successful /s']

In [27]:
test_l = test_l.drop(columns=['Percentage of full games played'])
test_l.head()

,Team,Position,Name,Games played,Full games played,Games started,Percentage of games started,Games where substituted,Percentage of games where substituted,Yellow Cards,...,Corners,Tackles.1,Duels,Man-to-man duels,Aerial duels,Passes,Short passes,Long passes,Through balls,Goals scored per attempt
0,Athletic Club,Goalkeeper,Hodei Oleaga,0,0,0,"0,0%",0,"0,0%",0,...,0,0,0,0,0,0.0,0.0,0,0,0
1,Athletic Club,Goalkeeper,A. Remiro,0,0,0,"0,0%",0,"0,0%",0,...,0,0,0,0,0,0.0,0.0,0,0,0
2,Athletic Club,Goalkeeper,Herrerín,31,31,31,"82,0%",0,"0,0%",1,...,0,0,25,6,19,887.0,128.0,759,1,0
3,Athletic Club,Goalkeeper,Unai Simón,7,7,7,"18,0%",0,"0,0%",2,...,0,0,3,2,1,155.0,49.0,106,0,0
4,Athletic Club,Defender,Núñez,12,11,11,"29,0%",1,"3,0%",4,...,0,15,107,38,69,536.0,457.0,78,1,0

In [3]:
test_f[(test_f['long_name'] == "Ethan Ampadu")]

,sofifa_id,player_url,short_name,long_name,age,dob,height_cm,weight_kg,nationality,club,...,lwb,ldm,cdm,rdm,rwb,lb,lcb,cb,rcb,rb
7691,235735,https://sofifa.com/player/235735/ethan-ampadu/...,E. Ampadu,Ethan Ampadu,18,2000-09-14,182,72,Wales,RB Leipzig,...,59+2,65+2,65+2,65+2,59+2,60+2,65+2,65+2,65+2,60+2

In [4]:
#import and transform the data
fifa = pd.read_csv('fifa.csv')
pl = pd.read_json('pl.json').transpose()
ll = pd.read_csv('ll.csv')
plClean = pl.reset_index()
plClean.rename(columns = {'index':'Name'}, inplace = True)

In [115]:
ll.columns

Index(['club', 'Position', 'club', 'Minutes played', 'Appearances',
       'Yellow cards', 'Red cards', 'Second Yellows', 'Goals',
       'Penalties scored', 'Own goals', 'Goals conceded while player on pitch',
       'Tackles', 'Interceptions', 'Recoveries', 'Clearances',
       'Successful tackles', 'Unssuccessful tackles', 'Last man',
       'Successful 50/50s', 'Duels lost', 'Successful aerial challenges',
       'Unsuccessful aerial challenges', 'Offsides', 'Fouls suffered', 'Fouls',
       'Penalties won', 'Penalties given away', 'Handballs committed',
       'Fouls committed per card', 'Shots', 'Shots on target', 'Assists',
       'Successful dribbles', 'Unsuccessful dribbles', 'Goals scored.1',
       'From inside the area', 'From outside the area', 'Goals with left foot',
       'Goals with right foot', 'Penalties scored.1', 'Headed goals',
       'Goals from set piece', 'Crosses', 'Corners', 'Tackles.1', 'Duels',
       'Man-to-man duels', 'Aerial duels', 'Passes', 'Short passes',
       'Long passes', 'Through balls', 'Goals scored per attempt'],
      dtype='object')

In [99]:
#llClean = llClean.rename(columns={"Unsuccessful aerial challenges":"Aerial battles lost"})
#llClean['Duels won'] = llClean['Duels'] - llClean['Duels lost']
#llClean = llClean.drop(columns=['Successful 50/50s'])
llClean.columns

Index(['club', 'Position', 'name', 'Minutes played', 'Appearances',
       'Yellow cards', 'Red cards', 'Second Yellows', 'Goals',
       'Penalties scored', 'Own goals', 'Goals conceded while player on pitch',
       'Tackles', 'Interceptions', 'Recoveries', 'Clearances',
       'Successful tackles', 'Unssuccessful tackles', 'Last man', 'Duels lost',
       'Successful aerial challenges', 'Aerial battles lost', 'Offsides',
       'Fouls suffered', 'Fouls', 'Penalties won', 'Penalties given away',
       'Handballs committed', 'Fouls committed per card', 'Shots',
       'Shots on target', 'Assists', 'Successful dribbles',
       'Unsuccessful dribbles', 'Goals scored.1', 'From inside the area',
       'From outside the area', 'Goals with left foot',
       'Goals with right foot', 'Penalties scored.1', 'Headed goals',
       'Goals from set piece', 'Crosses', 'Corners', 'Tackles.1', 'Duels',
       'Man-to-man duels', 'Aerial duels', 'Passes', 'Short passes',
       'Long passes', 'Through balls', 'Goals scored per attempt',
       'Tackle success %', 'Duels won'],
      dtype='object')

In [103]:
#llClean = llClean.drop(columns=['Successful 50/50s'])
llClean.head(50)

,club,Position,name,Minutes played,Appearances,Yellow cards,Red cards,Second Yellows,Goals,Penalties scored,...,Duels,Man-to-man duels,Aerial duels,Passes,Short passes,Long passes,Through balls,Goals scored per attempt,Tackle success %,Duels won
0,Athletic Club,Goalkeeper,Hodei Oleaga,0.000,0,0,0,0,0,0,...,0,0,0,0.000,0.000,0,0,0,NaN,0
1,Athletic Club,Goalkeeper,A. Remiro,0.000,0,0,0,0,0,0,...,0,0,0,0.000,0.000,0,0,0,NaN,0
2,Athletic Club,Goalkeeper,Herrerín,2.790,31,1,0,0,0,0,...,25,6,19,887.000,128.000,759,1,0,NaN,22
3,Athletic Club,Goalkeeper,Unai Simón,630.000,7,2,0,0,0,0,...,3,2,1,155.000,49.000,106,0,0,NaN,1
4,Athletic Club,Defender,Núñez,1.063,12,4,0,0,0,0,...,107,38,69,536.000,457.000,78,1,0,0.733333,88
5,Athletic Club,Defender,I. Martínez,2.903,33,12,0,0,0,0,...,329,162,167,1.440,1.074,361,5,0,0.490566,275
6,Athletic Club,Defender,Yeray,2.614,30,10,0,0,0,0,...,296,126,170,1.284,1.051,233,0,0,0.545455,246
7,Athletic Club,Defender,San José,1.716,33,7,0,0,0,0,...,243,141,102,707.000,637.000,64,6,0,0.595238,154
8,Athletic Club,Defender,Yuri B.,3.120,35,9,1,0,2,0,...,373,254,119,1.367,1.273,92,2,1,0.680851,273
9,Athletic Club,Defender,I. Lekue,210.000,4,1,0,0,0,0,...,29,20,9,85.000,75.000,10,0,0,0.400000,19
10,Athletic Club,Defender,Balenziaga,520.000,11,0,0,0,0,0,...,35,26,9,177.000,150.000,27,0,0,0.600000,22
11,Athletic Club,Midfielder,Nolaskoain,465.000,8,2,1,0,2,0,...,51,24,27,276.000,253.000,23,0,2,0.727273,40
12,Athletic Club,Midfielder,Beñat,2.045,27,8,0,0,1,0,...,208,170,38,1.166,1.013,151,2,1,0.510638,110
13,Athletic Club,Midfielder,Iturraspe,97.000,3,1,0,0,0,0,...,13,6,7,80.000,77.000,3,0,0,1.000000,10
14,Athletic Club,Midfielder,Córdoba,1.322,23,4,0,0,0,0,...,236,194,42,406.000,376.000,28,2,0,0.621622,130
15,Athletic Club,Midfielder,Susaeta,1.380,22,2,1,1,1,0,...,139,117,22,524.000,503.000,21,0,1,0.588235,68
16,Athletic Club,Midfielder,Dani García,2.482,29,13,0,0,0,0,...,268,177,91,1.396,1.201,195,0,0,0.596491,176
17,Athletic Club,Midfielder,Mikel Rico,243.000,4,0,0,0,0,0,...,40,26,14,94.000,87.000,7,0,0,0.400000,22
18,Athletic Club,Midfielder,De Marcos,2.426,30,4,2,1,1,0,...,252,181,71,1.028,934.000,94,0,1,0.533333,151
19,Athletic Club,Midfielder,Ibai,2.033,32,0,0,0,3,0,...,153,125,28,717.000,631.000,82,4,1,0.550000,78
20,Athletic Club,Midfielder,Capa,1.637,25,9,0,0,0,0,...,226,178,48,686.000,591.000,95,0,0,0.627907,124
21,Athletic Club,Midfielder,Raúl García,2.379,33,13,0,0,9,2,...,626,294,332,892.000,799.000,85,8,4,0.639344,458
22,Athletic Club,Midfielder,Unai López,325.000,7,1,0,0,0,0,...,40,31,9,242.000,213.000,29,0,0,0.750000,26
23,Athletic Club,Midfielder,Iñigo Vicente,0.000,0,0,0,0,0,0,...,0,0,0,0.000,0.000,0,0,0,NaN,0
24,Athletic Club,Forward,Gorka Guruzeta,45.000,6,0,0,0,0,0,...,20,7,13,9.000,9.000,0,0,0,1.000000,14
25,Athletic Club,Forward,Kenan Kodro,151.000,11,0,0,0,1,0,...,33,18,15,46.000,45.000,1,0,1,0.333333,21
26,Athletic Club,Forward,Williams,3.036,38,3,0,0,13,0,...,449,272,177,686.000,666.000,12,8,7,0.666667,304
27,Athletic Club,Forward,Muniain,2.385,34,7,0,0,7,1,...,344,308,36,1.187,1.126,51,10,6,0.678571,205
28,Athletic Club,Forward,Aduriz,941.000,20,4,0,0,2,2,...,167,55,112,230.000,227.000,3,0,1,0.250000,125
29,Atlético de Madrid,Goalkeeper,Alex Dos Santos,0.000,0,0,0,0,0,0,...,0,0,0,0.000,0.000,0,0,0,NaN,0
30,Atlético de Madrid,Goalkeeper,Adán,90.000,1,1,0,0,0,0,...,0,0,0,22.000,5.000,17,0,0,NaN,0
31,Atlético de Madrid,Goalkeeper,Oblak,3.330,37,0,0,0,0,0,...,14,6,8,759.000,147.000,612,0,0,0.000000,13
32,Atlético de Madrid,Defender,Godín,2.507,30,7,0,0,3,0,...,275,129,146,1.047,862.000,184,1,3,0.576923,226
33,Atlético de Madrid,Defender,Filipe Luis,2.037,27,4,0,0,2,0,...,206,178,28,1.287,1.164,123,0,2,0.545455,131
34,Atlético de Madrid,Defender,Arias,1.770,25,4,0,0,1,0,...,211,130,81,790.000,744.000,46,0,1,0.666667,168
35,Atlético de Madrid,Defender,Savić,1.399,18,3,1,1,0,0,...,96,36,60,544.000,425.000,119,0,0,0.909091,78
36,Atlético de Madrid,Defender,Nehuen Pérez,0.000,0,0,0,0,0,0,...,0,0,0,0.000,0.000,0,0,0,NaN,0
37,Atlético de Madrid,Defender,Juanfran,1.609,22,7,0,0,0,0,...,133,108,25,770.000,717.000,53,0,0,0.611111,82
38,Atlético de Madrid,Defender,L. Hernández,1.118,14,5,0,0,1,0,...,121,86,35,509.000,443.000,66,0,1,0.714286,95
39,Atlético de Madrid,Defender,J. M. Giménez,1.772,21,5,0,0,0,0,...,154,71,83,718.000,542.000,175,1,0,0.576923,133
40,Atlético de Madrid,Defender,Andrés Solano,45.000,1,0,0,0,0,0,...,6,5,1,26.000,24.000,2,0,0,0.750000,6
41,Atlético de Madrid,Defender,Francisco Montero,401.000,9,2,0,0,0,0,...,22,16,6,160.000,120.000,40,0,0,0.500000,15
42,Atlético de Madrid,Defender,Manuel Sánchez,0.000,0,0,0,0,0,0,...,0,0,0,0.000,0.000,0,0,0,NaN,0
43,Atlético de Madrid,Midfielder,Thomas,2.064,32,7,1,1,3,0,...,276,203,73,1.327,1.197,122,8,2,0.636364,194
44,Atlético de Madrid,Midfielder,Koke,2.587,30,8,1,1,3,0,...,293,261,32,1.941,1.760,167,14,3,0.547619,167
45,Atlético de Madrid,Midfielder,Saúl,2.925,33,10,0,0,4,0,...,448,288,160,1.483,1.358,121,4,2,0.674699,301
46,Atlético de Madrid,Midfielder,Rodrigo,2.742,34,5,0,0,3,0,...,402,287,115,1.927,1.776,150,1,2,0.679612,278
47,Atlético de Madrid,Midfielder,Cristian Rodríguez,0.000,0,0,0,0,0,0,...,0,0,0,0.000,0.000,0,0,0,NaN,0
48,Atlético de Madrid,Midfielder,Mikel Carro,0.000,0,0,0,0,0,0,...,0,0,0,0.000,0.000,0,0,0,NaN,0
49,Atlético de Madrid,Midfielder,Borja Garcés,19.000,1,0,0,0,1,0,...,1,0,1,4.000,4.000,0,0,1,NaN,1

In [5]:
#tokenize the name fields in fifa and plClean datasets
plClean['Name'] = plClean['Name'].str.split(" ")
fifa['long_name'] = fifa['long_name'].str.split(" ")

plClean['Name'] = plClean['Name'].apply(frozenset)
fifa['long_name'] = fifa['long_name'].apply(frozenset)

In [107]:
llClean['name'] = llClean['name'].str.split(" ")
llClean['name'] = llClean['name'].apply(frozenset)

In [6]:
#create a copy of the data for merging

fifa_copy = fifa

#iterate through PL data and match fifa player to current PL player
#update the name of the fifa player to reflect the PL data player name
for pl_row in plClean.iterrows():
    
    name = pl_row[1]['Name']
    club = pl_row[1]['Club']
    index_val = fifa_copy[(fifa_copy['long_name'].map(name.issubset)) & (fifa_copy['club'] == club)].index
    if len(index_val.tolist()) > 0:
        index_int = index_val.tolist()[0]
        
        fifa_copy.at[index_int, 'long_name'] = name

In [108]:
#create a copy of the data for merging

fifa_copy = fifa

#iterate through PL data and match fifa player to current PL player
#update the name of the fifa player to reflect the PL data player name
for ll_row in llClean.iterrows():
    
    name = ll_row[1]['name']
    club = ll_row[1]['club']
    index_val = fifa_copy[(fifa_copy['long_name'].map(name.issubset)) & (fifa_copy['club'] == club)].index
    if len(index_val.tolist()) > 0:
        index_int = index_val.tolist()[0]
        
        fifa_copy.at[index_int, 'long_name'] = name

In [7]:
#rename columns so that an outer join can be performed
fifa_copy = fifa_copy.rename(columns={'long_name' : 'name'} )
plClean = plClean.rename(columns={'Name' : 'name', 'Club':'club'})

In [111]:
#ll merge on name and club
fifa_copy = fifa_copy.rename(columns={'long_name' : 'name'} )

resultll = pd.merge(llClean, fifa_copy, how="outer", on=['name', 'club'])

In [112]:
#merge on name and club
result = pd.merge(plClean, fifa_copy, how="outer", on=['name', 'club'])

In [113]:
#these dataframes have all of the data from the premier league set and the fifa set
plKeeper = result[(result.Position == "Goalkeeper")]
plForward = result[(result.Position == "Forward")]
plMid = result[(result.Position == "Midfielder")]
plDefender = result[(result.Position == "Defender")]

In [114]:
#these dataframes have all of the data from the premier league set and the fifa set
llKeeper = resultll[(resultll.Position == "Goalkeeper")]
llForward = resultll[(resultll.Position == "Forward")]
llMid = resultll[(resultll.Position == "Midfielder")]
llDefender = resultll[(resultll.Position == "Defender")]

In [12]:
result.head(50)

,name,club,Position,Appearances,Goals,Wins,Losses,Attack,Goals Per Match,Goals With Header,...,lwb,ldm,cdm,rdm,rwb,lb,lcb,cb,rcb,rb
0,"(Aarons, Rolando)",Newcastle United,Midfielder,14,2,3,9,,0.14,1,...,56+2,51+2,51+2,51+2,56+2,53+2,44+2,44+2,44+2,53+2
1,"(Tammy, Abraham)",Swansea City,Forward,33,5,6,18,,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"(Smith, Adam)",AFC Bournemouth,Defender,96,4,30,40,,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,(Adrián),West Ham United,Goalkeeper,125,0,45,44,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"(Silva, Adrien)",Leicester City,Midfielder,13,0,3,7,,NaN,NaN,...,73+3,75+3,75+3,75+3,73+3,71+3,69+3,69+3,69+3,71+3
5,"(Benik, Afobe)",Stoke City,Forward,63,10,19,28,,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,"(Sergio, Agüero)",Manchester City,Forward,207,143,134,35,,NaN,NaN,...,60+3,58+3,58+3,58+3,60+3,56+3,50+3,50+3,50+3,56+3
7,"(Daniel, Agyei)",Blackpool,Forward,3,0,0,3,,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,"(Aké, Nathan)",AFC Bournemouth,Defender,80,6,32,32,,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,"(Chuba, Akpom)",Hull City,Forward,4,0,2,2,,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,"(Albrighton, Marc)",Leicester City,Midfielder,209,15,71,77,,NaN,NaN,...,68+2,67+2,67+2,67+2,68+2,65+2,60+2,60+2,60+2,65+2
11,"(Alderweireld, Toby)",Tottenham Hotspur,Defender,108,6,62,21,,NaN,NaN,...,78+3,83+3,83+3,83+3,78+3,80+3,84+3,84+3,84+3,80+3
12,"(García, Aleix)",Girona,Midfielder,4,0,2,0,,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,"(Alexander-Arnold, Trent)",Liverpool,Defender,27,1,16,4,,NaN,NaN,...,81+2,79+2,79+2,79+2,81+2,80+2,76+2,76+2,76+2,80+2
14,(Alisson),Liverpool,Goalkeeper,1,0,1,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,"(McGregor, Allan)",Hull City,Goalkeeper,52,0,12,27,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,"(Souza, Allan)",Eintracht Frankfurt,Midfielder,0,0,0,0,,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,"(Marcos, Alonso)",Chelsea,Defender,90,14,56,21,,NaN,NaN,...,80+2,79+2,79+2,79+2,80+2,79+2,78+2,78+2,78+2,79+2
18,"(Daniel, Amartey)",Leicester City,Midfielder,38,1,13,16,,NaN,NaN,...,71+2,72+2,72+2,72+2,71+2,71+2,75+2,75+2,75+2,71+2
19,"(Amos, Luke)",Stevenage,Midfielder,1,0,1,0,,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,"(Ethan, Ampadu)",Chelsea,Defender,1,0,1,0,,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,"(Nordin, Amrabat)",Leganés,Forward,44,0,12,23,,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,"(Anderson, Tom)",Doncaster Rovers,Defender,0,0,0,0,,NaN,NaN,...,49+2,55+2,55+2,55+2,49+2,51+2,63+2,63+2,63+2,51+2
23,"(Florin, Andone)",Brighton and Hove Albion,Forward,0,0,0,0,,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,"(Gomes, André)",Everton,Midfielder,0,0,0,0,,NaN,NaN,...,73+3,78+3,78+3,78+3,73+3,72+3,74+3,74+3,74+3,72+3
25,"(Andreas, Pereira)",Valencia CF,Midfielder,6,0,4,2,,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,"(Antonio, Michail)",West Ham United,Midfielder,77,20,27,29,,NaN,NaN,...,67+2,66+2,66+2,66+2,67+2,66+2,65+2,65+2,65+2,66+2
27,"(Antonio, Valencia)",Manchester United,Defender,319,24,176,77,,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,"(Armstrong, Adam)",Blackburn Rovers,Forward,15,0,1,13,,NaN,NaN,...,53+2,50+2,50+2,50+2,53+2,50+2,46+2,46+2,46+2,50+2
29,"(Marko, Arnautovic)",West Ham United,Forward,157,33,51,64,,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,"(Kepa, Arrizabalaga)",Chelsea,Goalkeeper,1,0,1,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,"(Harry, Arter)",Cardiff City,Midfielder,69,3,22,30,,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,"(Christian, Atsu)",Newcastle United,Midfielder,33,2,12,13,,NaN,NaN,...,57+2,52+2,52+2,52+2,57+2,54+2,42+2,42+2,42+2,54+2
33,"(Aubameyang, Pierre-Emerick)",Arsenal,Forward,14,10,7,7,,NaN,NaN,...,64+3,58+3,58+3,58+3,64+3,61+3,51+3,51+3,51+3,61+3
34,"(Serge, Aurier)",Tottenham Hotspur,Defender,17,2,12,2,,NaN,NaN,...,77+2,76+2,76+2,76+2,77+2,77+2,77+2,77+2,77+2,77+2
35,"(Austin, Charlie)",Southampton,Forward,82,32,21,42,,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,"(Jordan, Ayew)",Crystal Palace,Forward,80,15,16,47,,NaN,NaN,...,61+2,59+2,59+2,59+2,61+2,59+2,55+2,55+2,55+2,59+2
37,"(Floyd, Ayité)",Fulham,Forward,0,0,0,0,,NaN,NaN,...,54+2,51+2,51+2,51+2,54+2,51+2,45+2,45+2,45+2,51+2
38,"(Ayoze, Pérez)",Newcastle United,Forward,106,21,29,52,,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,"(César, Azpilicueta)",Chelsea,Defender,198,5,118,37,,NaN,NaN,...,81+3,82+3,82+3,82+3,81+3,81+3,81+3,81+3,81+3,81+3
40,"(Juninho, Bacuna)",Huddersfield Town,Midfielder,0,0,0,0,,NaN,NaN,...,68+2,69+2,69+2,69+2,68+2,66+2,67+2,67+2,67+2,66+2
41,"(Eric, Bailly)",Manchester United,Defender,39,1,25,5,,NaN,NaN,...,70+2,71+2,71+2,71+2,70+2,72+2,78+2,78+2,78+2,72+2
42,"(Leighton, Baines)",Everton,Defender,407,32,159,130,,NaN,NaN,...,73+3,74+3,74+3,74+3,73+3,72+3,73+3,73+3,73+3,72+3
43,"(Tiemoué, Bakayoko)",Milan,Midfielder,29,2,18,6,,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,"(Fabián, Balbuena)",West Ham United,Defender,1,0,0,1,,NaN,NaN,...,65+2,71+2,71+2,71+2,65+2,68+2,78+2,78+2,78+2,68+2
45,"(Baldock, Sam)",Reading,Forward,2,0,0,2,,NaN,NaN,...,52+2,48+2,48+2,48+2,52+2,50+2,44+2,44+2,44+2,50+2
46,"(Leon, Balogun)",Brighton and Hove Albion,Defender,0,0,0,0,,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,"(Baningime, Beni)",Everton,Midfielder,8,0,2,2,,NaN,NaN,...,63+2,66+2,66+2,66+2,63+2,63+2,64+2,64+2,64+2,63+2
48,"(Phil, Bardsley)",Burnley,Defender,259,7,83,114,,NaN,NaN,...,70+2,72+2,72+2,72+2,70+2,70+2,74+2,74+2,74+2,70+2
49,"(Barkley, Ross)",Chelsea,Midfielder,153,21,62,49,,NaN,NaN,...,66+2,68+2,68+2,68+2,66+2,64+2,63+2,63+2,63+2,64+2

In [13]:
#data available in all dataframes 
list(result.columns)

['name',
 'club',
 'Position',
 'Appearances',
 'Goals',
 'Wins',
 'Losses',
 'Attack',
 'Goals Per Match',
 'Goals With Header',
 'Goals With Right Foot',
 'Goals With Left Foot',
 'Penalties Scored',
 'Goals From Freekick',
 'Shots',
 'Shots On Target',
 'Shooting Accuracy %',
 'Hit Woodwork',
 'Big Chances Missed',
 'Team Play',
 'Assists',
 'Passes',
 'Passes Per Match',
 'Big Chances Created',
 'Crosses',
 'Cross Accuracy %',
 'Through Balls',
 'Accurate Long Balls',
 'Discipline',
 'Yellow Cards',
 'Red Cards',
 'Fouls',
 'Offsides',
 'Defence',
 'Tackles',
 'Tackle Success %',
 'Blocked Shots',
 'Interceptions',
 'Clearances',
 'Headed Clearance',
 'Recoveries',
 'Duels Won',
 'Duels Lost',
 'Successful 50/50s',
 'Aerial Battles Won',
 'Aerial Battles Lost',
 'Errors Leading To Goal',
 'Goals per match',
 'Headed goals',
 'Goals with right foot',
 'Goals with left foot',
 'Penalties scored',
 'Freekicks scored',
 'Shots on target',
 'Shooting accuracy %',
 'Hit woodwork',
 'Big chances missed',
 'Passes per match',
 'Big chances created',
 'Yellow cards',
 'Red cards',
 'Blocked shots',
 'Clean sheets',
 'Goals conceded',
 'Tackle success %',
 'Last man tackles',
 'Clearances off line',
 'Duels won',
 'Duels lost',
 'Aerial battles won',
 'Aerial battles lost',
 'Own goals',
 'Errors leading to goal',
 'Cross accuracy %',
 'Through balls',
 'Accurate long balls',
 'Goalkeeping',
 'Saves',
 'Penalties saved',
 'Punches',
 'High Claims',
 'Catches',
 'Sweeper clearances',
 'Throw outs',
 'Goal Kicks',
 'Successful 5/5s',
 'Successful 0/0s',
 'Successful /s',
 'sofifa_id',
 'player_url',
 'short_name',
 'age',
 'dob',
 'height_cm',
 'weight_kg',
 'nationality',
 'overall',
 'potential',
 'value_eur',
 'wage_eur',
 'player_positions',
 'preferred_foot',
 'international_reputation',
 'weak_foot',
 'skill_moves',
 'work_rate',
 'body_type',
 'real_face',
 'release_clause_eur',
 'player_tags',
 'team_position',
 'team_jersey_number',
 'loaned_from',
 'joined',
 'contract_valid_until',
 'nation_position',
 'nation_jersey_number',
 'pace',
 'shooting',
 'passing',
 'dribbling',
 'defending',
 'physic',
 'gk_diving',
 'gk_handling',
 'gk_kicking',
 'gk_reflexes',
 'gk_speed',
 'gk_positioning',
 'player_traits',
 'attacking_crossing',
 'attacking_finishing',
 'attacking_heading_accuracy',
 'attacking_short_passing',
 'attacking_volleys',
 'skill_dribbling',
 'skill_curve',
 'skill_fk_accuracy',
 'skill_long_passing',
 'skill_ball_control',
 'movement_acceleration',
 'movement_sprint_speed',
 'movement_agility',
 'movement_reactions',
 'movement_balance',
 'power_shot_power',
 'power_jumping',
 'power_stamina',
 'power_strength',
 'power_long_shots',
 'mentality_aggression',
 'mentality_interceptions',
 'mentality_positioning',
 'mentality_vision',
 'mentality_penalties',
 'mentality_composure',
 'defending_marking',
 'defending_standing_tackle',
 'defending_sliding_tackle',
 'goalkeeping_diving',
 'goalkeeping_handling',
 'goalkeeping_kicking',
 'goalkeeping_positioning',
 'goalkeeping_reflexes',
 'ls',
 'st',
 'rs',
 'lw',
 'lf',
 'cf',
 'rf',
 'rw',
 'lam',
 'cam',
 'ram',
 'lm',
 'lcm',
 'cm',
 'rcm',
 'rm',
 'lwb',
 'ldm',
 'cdm',
 'rdm',
 'rwb',
 'lb',
 'lcb',
 'cb',
 'rcb',
 'rb']